PREFIX vg: <http://biohackathon.org/resource/vg#>
PREFIX faldo: <http://biohackathon.org/resource/faldo#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
        ?link a vg:Link;
                vg:arrival ?arrivalbin;
                vg:departure ?departurebin;
                vg:linkPaths ?path .
        # THIS DOES NOT WORK AND I DON'T KNOW WHY ?path rdfs:label ?l .
        ?arrivalbin vg:binRank ?arrivalbinrank .
        ?departurebin vg:binRank ?departurebinrank .
        FILTER((?arrivalbinrank < 6 && ?arrivalbinrank > 0) || (?departurebinrank < 6 && ?departurebinrank > 0))
}